// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article_image: dynamic(() => import("./ArticleImage")),
  cover_image: dynamic(() => import("./CoverImage")),
  quote: dynamic(() => import("./Quote")),
  text: dynamic(() => import("./Text")),
};
