// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  cover_image: dynamic(() => import("./CoverImage")),
  sepcial_article: dynamic(() => import("./SepcialArticle")),
};
